# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Reference: https://pimylifeup.com/ubuntu-install-godot/
      - name: Install Dependencies and Prepare for Export
        # The wget package is what we will use to download the Godot archive.
        # We will then have to use the unzip package to extract the archive’s contents.
        run: |
          sudo apt install wget unzip
          wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          sudo chmod +x butler
          wget https://github.com/godotengine/godot/releases/download/4.2-stable/Godot_v4.2-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip
          sudo mv Godot_v4.2-stable_linux.x86_64 /usr/local/bin/
          sudo mv /usr/local/bin/Godot_v4.2-stable_linux.x86_64 /usr/local/bin/godot
          sudo chmod a+x /usr/local/bin/godot

      - name: Export Godot Project
        # "Windows" should be the name of the Export Template
        run: godot --headless --export-debug "Windows" SpaceDeliverySquad.exe

      - name: Zip Export to Prepare for Itch Upload
        run: zip SDS SpaceDeliverySquad.exe SpaceDeliverySquad.console.exe SpaceDeliverySquad.pck
        
      - name: Itch.io - Publish
        # You may pin to the exact commit or the version.
        # uses: KikimoraGames/itch-publish@ea06fdc7e36b34a6c4f88b379a73f3362537b998
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          # Butler API Key
          butlerApiKey: # TODO: https://itch.io/docs/butler/login.html#running-butler-from-ci-builds-travis-ci-gitlab-ci-etc
          # Directory or .zip file of the game data. Zip files are slower to upload.
          gameData: ./SDS.zip
          # Itch.io username of the game owner. e.g. in finji/overland this would be finji.
          itchUsername: tylerwalton
          # Itch.io id of the game. e.g. in finji/overland this would be overland.
          itchGameId: 2410890
          # Channel name of the game: https://itch.io/docs/butler/pushing.html#channel-names
          buildChannel: windows
          # Optional build number, use to supply your own build version instead of using itch's versioning
          buildNumber: 0.0.1
          
